/* parametry.h */ 


//PRZERWY CZASOWE 
#define CZAS_PAUZY_1		100
#define CZAS_PAUZY_2		200
#define CZAS_PAUZY_3		400
#define CZAS_PAUZY_BOMPOS		1000


//pozycje kursora
//------------------------------------------------------------------------------

//PUSTE POLE SAP 1
#define PUSTE_POLE_SAP_1		500, 500

//PUSTE POLE SAP 2
#define PUSTE_POLE_SAP_2		1400, 400

//TWORZENIE MATERIA£U - SORTOWANIE
#define TWORZENIE_MATERIALU_SORTOWANIE		1480, 150

//TWORZENIE MATERIA£U - SORTOWANIE MALEJ¥CE
#define TWORZENIE_MATERIALU_SORTOWANIE_MALEJACE		1480, 370

//KLASYFIKACJA - ZAZNACZANIE KLASY
#define KLASYFIKACJA_ZAZNACZANIE_KLASY  790, 270

//KLASYFIKACJA - USUWANIE KLASY
#define KLASYFIKACJA_USUWANIE_KLASY  945, 350

//PROFIL KONFIGURACJI - WYBÓR OBIEKTÓW KONFIGUROWALNYCH
#define PROFIL_KONFIGURACJI_WYBOR_OBIEKTOW_KONFIGUROWALNYCH		900, 283	


//rozpoznawanie koloru
//------------------------------------------------------------------------------

//SZARA STRZA£KA POLA G£OWNEGO
#define STRZALKA_POLA_GLOWNEGO_OS_X		1285
#define STRZALKA_POLA_GLOWNEGO_OS_Y		150

//ZIELONY ZNACZEK POLA G£OWNEGO  
#define ZIELONY_ZNACZEK_POLA_GLOWNEGO_OS_X      975
#define ZIELONY_ZNACZEK_POLA_GLOWNEGO_OS_Y      1003

//POMARAÑCZOWY ZNACZEK POLA G£OWNEGO  
#define POMARANCZOWY_ZNACZEK_POLA_GLOWNEGO_OS_X      974
#define POMARANCZOWY_ZNACZEK_POLA_GLOWNEGO_OS_Y      1006	

//------------------------------------------------------------------------------

//TWORZENIE MATERIA£U - SZUKANIE
#define TWORZENIE_MATERIALU_SZUKANIE_OS_X		1500
#define TWORZENIE_MATERIALU_SZUKANIE_OS_Y		220

//TWORZENIE MATERIA£U - SZUKANIE INDEKSU 1
#define TWORZENIE_MATERIALU_SZUKANIE_INDEKSU_1_OS_X		1500
#define TWORZENIE_MATERIALU_SZUKANIE_INDEKSU_1_OS_Y		960

//TWORZENIE MATERIA£U - SZUKANIE INDEKSU 2
#define TWORZENIE_MATERIALU_SZUKANIE_INDEKSU_2_OS_X		1500
#define TWORZENIE_MATERIALU_SZUKANIE_INDEKSU_2_OS_Y		10

//TWORZENIE MATERIA£U - WYBÓR WGL¥DÓW
#define TWORZENIE_MATERIALU_WYBOR_WGLADOW_OS_X		1500
#define TWORZENIE_MATERIALU_WYBOR_WGLADOW_OS_Y		240

//TWORZENIE MATERIA£U - POZIOMY ORGANIZACYJNE
#define TWORZENIE_MATERIALU_POZIOMY_ORGANIZACYJNE_OS_X		1500
#define TWORZENIE_MATERIALU_POZIOMY_ORGANIZACYJNE_OS_Y		210

//TWORZENIE MATERIA£U - DANE PODSTAWOWE 1
#define TWORZENIE_MATERIALU_DANE_PODSTAWOWE_1_OS_X		1150
#define TWORZENIE_MATERIALU_DANE_PODSTAWOWE_1_OS_Y		190	

//TWORZENIE MATERIA£U - HIERARCHIA PRODUKTU
#define TWORZENIE_MATERIALU_HIERARCHIA_PRODUKTU_OS_X		1400
#define TWORZENIE_MATERIALU_HIERARCHIA_PRODUKTU_OS_Y		440	

//TWORZENIE MATERIA£U - DANE PODSTAWOWE PROD
#define TWORZENIE_MATERIALU_DANE_DODATKOWE_PROD_1_OS_X		1365
#define TWORZENIE_MATERIALU_DANE_DODATKOWE_PROD_1_OS_Y		190	

//TWORZENIE MATERIA£U - KLASYFIKACJA
#define TWORZENIE_MATERIALU_KLASYFIKACJA_OS_X		1400
#define TWORZENIE_MATERIALU_KLASYFIKACJA_OS_Y		315
		
//TWORZENIE MATERIA£U - KLASYFIKACJA - USUWANIE MATERIA£U
#define TWORZENIE_MATERIALU_KLASYFIKACJA_USUWANIE_MATERIALU_OS_X		1500
#define TWORZENIE_MATERIALU_KLASYFIKACJA_USUWANIE_MATERIALU_OS_Y		320			
				
//TWORZENIE MATERIA£U - MRP1
#define TWORZENIE_MATERIALU_MRP1_OS_X		1225
#define TWORZENIE_MATERIALU_MRP1_OS_Y		190

//TWORZENIE MATERIA£U - MRP2
#define TWORZENIE_MATERIALU_MRP2_OS_X		1150
#define TWORZENIE_MATERIALU_MRP2_OS_Y		190	

//TWORZENIE MATERIA£U - DZIA£ SPRZEDA¯Y 1 1
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_1_1_OS_X		1290
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_1_1_OS_Y		190	

//TWORZENIE MATERIA£U - DZIA£ SPRZEDA¯Y 1 1
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_1_2_OS_X		1260
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_1_2_OS_Y		190	

//TWORZENIE MATERIA£U - DZIA£ SPRZEDA¯Y 2
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_2_OS_X		1340
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_2_OS_Y		190

//TWORZENIE MATERIA£U - ZAPISANIE
#define TWORZENIE_MATERIALU_ZAPISANIE_OS_X		1500
#define TWORZENIE_MATERIALU_ZAPISANIE_OS_Y		320			

//------------------------------------------------------------------------------

//PROFIL KONFIGURACJI - KOPIOWANIE WZORCA
#define PROFIL_KONFIGURACJI_KOPIOWANIE_WZORCA_OS_X		1540
#define PROFIL_KONFIGURACJI_KOPIOWANIE_WZORCA_OS_Y		290	

//PROFIL KONFIGURACJI - KOPIOWANIE WZORCA - POTWIERDZENIE
#define PROFIL_KONFIGURACJI_KOPIOWANIE_WZORCA_POTWIERDZENIE_OS_X		1500
#define PROFIL_KONFIGURACJI_KOPIOWANIE_WZORCA_POTWIERDZENIE_OS_Y		520	

//------------------------------------------------------------------------------

//TWORZENIE KLASY - WZORZEC KLASA
#define TWORZENIE_KLASY_WZORZEC_KLASA_OS_X		1200
#define TWORZENIE_KLASY_WZORZEC_KLASA_OS_Y		320	

//------------------------------------------------------------------------------

//PRZYPISANIE DO KLASY - DODANIE MATERIA£U
#define PRZYPISANIE_DO_KLASY_DODANIE_MATERIALU_OS_X		1670
#define PRZYPISANIE_DO_KLASY_DODANIE_MATERIALU_OS_Y		340	

//------------------------------------------------------------------------------

//WYWO£ANIE OPRACOWANIA WGL¥DÓW
#define WYWOLANIE_OPRACOWANIA_WGLADOW_OS_X		1170
#define WYWOLANIE_OPRACOWANIA_WGLADOW_OS_Y		440	

//WYWO£ANIE OPRACOWANIA WGL¥DÓW - TABELA BOMPOS
#define WYWOLANIE_OPRACOWANIA_WGLADOW_TABELA_BOMPOS_OS_X		1700
#define WYWOLANIE_OPRACOWANIA_WGLADOW_TABELA_BOMPOS_OS_Y		210	

//------------------------------------------------------------------------------

//TWORZENIE SPECYFIKACJI MATERIA£OWEJ - KOPIOWANIE WZORCA
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_KOPIOWANIE_WZORCA_OS_X		1350
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_KOPIOWANIE_WZORCA_OS_Y		340	

//TWORZENIE SPECYFIKACJI MATERIA£OWEJ - WZORZEC
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_WZORZEC_OS_X		1350
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_WZORZEC_OS_Y		315	

//TWORZENIE SPECYFIKACJI MATERIA£OWEJ
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_OS_X		1600
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_OS_Y		390	

//------------------------------------------------------------------------------

//STANDARDOWA MARSZRUTA - ZMIANA - PRZEGL¥D OPERACJI
#define STANDARDOWA_MARSZRUTA_ZMIANA_PRZEGLAD_OPERACJI_OS_X		1540
#define STANDARDOWA_MARSZRUTA_ZMIANA_PRZEGLAD_OPERACJI_OS_Y		290	

//STANDARDOWA MARSZRUTA - ZMIANA - PE£EN NAG£ÓWEK
#define STANDARDOWA_MARSZRUTA_ZMIANA_PELEN_NAGLOWEK_OS_X		1540
#define STANDARDOWA_MARSZRUTA_ZMIANA_PELEN_NAGLOWEK_OS_Y		290	

//STANDARDOWA MARSZRUTA - ZMIANA - PRZYPISANIE MATERIA£U
#define STANDARDOWA_MARSZRUTA_ZMIANA_PRZYPISANIE_MATERIALU_OS_X		1350
#define STANDARDOWA_MARSZRUTA_ZMIANA_PRZYPISANIE_MATERIALU_OS_Y		220	

//STANDARDOWA MARSZRUTA - ZMIANA - PRZYPISANIE SK£ADNIKÓW
#define STANDARDOWA_MARSZRUTA_ZMIANA_PRZYPISANIE_SKLADNIKOW_OS_X		1350
#define STANDARDOWA_MARSZRUTA_ZMIANA_PRZYPISANIE_SKLADNIKOW_OS_Y		290	

//STANDARDOWA MARSZRUTA - ZMIANA - PONOWNE PRZYPISANIE
#define STANDARDOWA_MARSZRUTA_ZMIANA_PONOWNE_PRZYPISANIE_OS_X		1350
#define STANDARDOWA_MARSZRUTA_ZMIANA_PONOWNE_PRZYPISANIE_OS_Y		290	

//------------------------------------------------------------------------------


// kolory do rozpoznania

//SZARY 1
#define KOLOR_SZARY_1_RGB_1		a != 234 and b != 237 and c != 240

//SZARY 2
#define KOLOR_SZARY_2_RGB_1		a != 102 and b != 102 and c != 102
#define KOLOR_SZARY_2_RGB_2		a == 102 and b == 102 and c == 102

//SZARY 3
#define KOLOR_SZARY_3_RGB_1		a != 247 and b != 247 and c != 247

//SZARY 4
#define KOLOR_SZARY_4_RGB_1		a != 229 and b != 229 and c != 229

//SZARY 5
#define KOLOR_SZARY_5_RGB_1		a != 249 and b != 249 and c != 249

//SZARY 6
#define KOLOR_SZARY_6_RGB_1		a != 236 and b != 236 and c != 236

//ZIELONY - IKONA
#define KOLOR_ZIELONY_1_RGB_1		a != 0 and b != 139 and c != 0

//NIEBIESKI
#define KOLOR_NIEBIESKI_1_RGB_1	a != 0 and b != 157 and c != 224

//NIEBIESKI
#define KOLOR_NIEBIESKI_1_RGB_2	a == 0 and b == 157 and c == 224

//BIA£Y
#define KOLOR_BIALY_1_RGB_1		a != 255 and b != 255 and c != 255

//POMARAÑCZOWY
#define KOLOR_POMARANCZOWY_1_RGB_1	a != 255 and b != 187 and c != 51

//POMARAÑCZOWY
#define KOLOR_POMARANCZOWY_1_RGB_2	a == 255 and b == 187 and c == 51

